version: '3.8'

networks:
  gv-network:
    driver: bridge

volumes:
  prometheus_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5443:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas
  prometheus:
    container_name: gestao_vagas_prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    depends_on:
      - postgres
    networks:
      - gv-network
#  sonarqube:
#    image: sonarqube:9.9.0-community
#    container_name: gestao_vagas_sonarqube
#    environment:
#      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
#    ports:
#      - "9001:9000"
#    restart: always